from pathlib import Path
p=Path('extras/mounts/medium/workshop/app.js');s=p.read_text()
s=s.replace('let canvasPoint=null,activeDial=null;', 'let canvasPoint=null,activeDial=null,undoing=false;')
s=s.replace('function renderItem(b,force=false){if(fieldDrag)return;', 'function renderItem(b,force=false){if(fieldDrag||activeDial===b.id)return;')
s=s.replace("control.onfocus=()=>{if(b.editExisting){", "control.onfocusin=()=>{if(b.editExisting&&!b.valueDirty){")
s=s.replace("input.properties={value:{mode:'input',field:field.label,slot:field.slot}}", "input.properties={value:{mode:field.writable===false?'source':'input',field:field.label,slot:field.slot,readonly:field.writable===false}}")
s=s.replace("if(b.editExisting&&!selection(b))control.disabled=true;", "if(property(b,'value').readonly||b.editExisting&&!selection(b))for(const item of [control,...control.querySelectorAll('input,button,select,textarea')])item.disabled=true;")
s=s.replace("if(p.mode!=='input'||!p.field)throw Error('Choose the write field for '+title(input));", "if(p.mode==='source')continue;if(p.mode!=='input'||!p.field)throw Error('Choose the write field for '+title(input));")
old="const current=nativeRows(id).find(r=>r.id===selectedId);const all=Object.fromEntries(fields(button).map(f=>[f,values[f]??current?.[f]??'']));await collectionCall({action:'update',collection:id,record:selectedId,values:all,before:Object.fromEntries(edits.map(e=>[e.field,e.input.draftBefore])),event:uid()});"
new="await collectionCall({action:'update',collection:id,record:selectedId,fields:edits.map(e=>e.field),values:Object.fromEntries(edits.map(e=>[e.field,e.value])),before:Object.fromEntries(edits.map(e=>[e.field,e.input.draftBefore])),event:uid()});"
assert old in s;s=s.replace(old,new).replace("refreshViews();return;}for(const edit of edits)","refreshViews();say('Saved selected record');log('Updated selected record in '+nativeName(id),'write','Only edited fields · one native transaction');return;}for(const edit of edits)")
old="undoStack.push({kind:'native',reason:body.action==='create'?'Create collection':body.action==='record'?'Add record':'Edit record',expected:nativeState.expected});"
new="if(!undoing)undoStack.push(body.action==='update'&&body.before&&Object.keys(body.before).length?{kind:'nativepatch',reason:'Edit record',collection:body.collection,record:body.record,component:body.component,before:clone(body.before),after:Object.fromEntries(Object.keys(body.before).map(k=>[k,String(body.values[k])]))}:{kind:'native',reason:body.action==='create'?'Create collection':body.action==='record'?'Add record':'Edit record',expected:nativeState.expected});"
assert old in s;s=s.replace(old,new)
old="const previous=undoStack.at(-1);if(previous?.kind==='native')"
new="const previous=undoStack.at(-1);if(previous?.kind==='nativepatch'){try{undoing=true;await nativeWork(async()=>{await collectionCall({action:'update',collection:previous.collection,record:previous.record,component:previous.component,fields:Object.keys(previous.before),values:previous.before,before:previous.after,event:uid()});undoStack.pop();refreshViews();say('Undid '+previous.reason);log('Undo '+previous.reason,'write','Scoped inverse · unrelated source updates preserved');},false);}catch(error){report(error);}finally{undoing=false;}return;}if(previous?.kind==='native')"
assert old in s;s=s.replace(old,new)
s=s.replace("choose.onclick=()=>{selected=b.id;showProperties('source');};", "choose.onclick=()=>{selected=b.id;pointing=b.id;showProperties('source');say('Click a collection in Namespace · data, or a source on the canvas');};")
s=s.replace("else if(b.part==='button'){const action=element('button',title(b),'run-action');action.onclick=()=>submitForm(b).catch(report);body.append(action,element('div',(b.action==='update'?'Updates ':'Creates ')+nativeName(collection(b)),'write-caption'));}", "else if(b.part==='button'){const action=element('button',title(b),'run-action');action.onclick=()=>b.action?submitForm(b).catch(report):say('This button needs a declared action and destination');body.append(action,element('div',b.action?(b.action==='update'?'Updates ':'Creates ')+nativeName(collection(b)):'→ ? what does this do',b.action?'write-caption':'effect-hole'));}")
p.write_text(s)
p=Path('extras/mounts/medium/workshop/style.css');p.write_text(p.read_text()+'\n.effect-hole{font-size:10px;color:#a67828;border:1px dashed #d7bc8a;border-radius:4px;display:inline-block;padding:4px;margin-top:5px}\n')
