#!/bin/sh

set -eu

archive=/tmp/enki-source.tar
workdir=/work

mkdir -p "$workdir"
tar -C /source \
  --exclude='./.git' \
  --exclude='./build' \
  --exclude='./result' \
  --exclude='./result-*' \
  --exclude='./snap' \
  --exclude='./reaver' \
  -cf "$archive" .
tar -C "$workdir" -xf "$archive"

exec "$workdir/tools/nix-ci" "path:$workdir"
