#!/bin/sh

set -eu

flake_ref=${1:-.}

nix --extra-experimental-features 'nix-command flakes' \
  flake check -L "$flake_ref"
nix --extra-experimental-features 'nix-command flakes' \
  build -L "${flake_ref}#default"
