#!/usr/bin/env python3
"""Generate the ordered Foil table from the unchanged rule fixture."""
import json,pathlib,sys
root=pathlib.Path(__file__).resolve().parents[1]
rows=json.loads((root/'rules/rules.json').read_text())
s='''- goo_app/types

' Generated by scripts/porting/generate-foil-rules.py; do not hand-edit.
+ goo_rules
  + rule
    : number=nat left=goo/slot right=goo/slot bind=goo/affinity
  + all
    ^ row[goo_rules/rule]
    [
'''
for r in rows:s+=f'     (goo_rules/rule {r["number"]} (goo/slot {json.dumps(r["left"])}) (goo/slot {json.dumps(r["right"])}) (goo/affinity/{r["bind"]}))\n'
s+='''    ]
  + find
    ' Preserve Map.fromList semantics: the final matching rule wins.
    \\ left=goo/slot right=goo/slot
    ^ maybe[goo_rules/rule]
    % i=nat 0 found=maybe[goo_rules/rule] .none
    ^ maybe[goo_rules/rule]
    ? (eq i (goo_rules/all).len) found
    = rule (goo_rules/all).at(i)
      match !(!(equal[goo/slot] left rule.left) || !(equal[goo/slot] right rule.right))
    | _ i.inc (? match (./some rule) found)
'''
p=root/'rules.foil'
if '--check' in sys.argv:
    if p.read_text()!=s:raise SystemExit('generated rule table is stale')
else:p.write_text(s)
