from pathlib import Path
p=Path('extras/mounts/medium/workshop/app.js');s=p.read_text()
start=s.index('function openMaterial(');end=s.index('function createForm(',start)
s=s[:start]+'''async function collectionCall(body){const response=await fetch('/api/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Native collection check failed');nativeState=result.frame;renderData();return result;}
function openMaterial(target=null){const b=add('frame');b.part='collection-editor';b.materialTarget=target;b.rect.w=370;b.rect.h=266;b.schemaFields=[{name:'',type:'Text',choices:[]}];b.creationEvent=uid();setTitle(b,'');save(b);render();reveal(b);nodes.get(b.id)?.querySelector('.collection-name')?.focus();}
function collectionEditor(b){
 const panel=element('section',undefined,'collection-editor'),header=element('div',undefined,'collection-editor-heading');header.dataset.handle='true';header.append(element('span','NEW COLLECTION','eyebrow'));const close=element('button','×');close.setAttribute('aria-label','Dismiss collection draft');close.onclick=()=>{b.archived=true;save(b);render();};header.append(close);panel.append(header);
 const name=element('input',undefined,'collection-name');name.placeholder='Collection name';name.setAttribute('aria-label','Collection name');name.value=b.content[0]?.text||'';name.oninput=()=>{setTitle(b,name.value);save(b);};panel.append(name);
 const labels=element('div',undefined,'schema-headings');labels.append(element('span','FIELD'),element('span','TYPE'));panel.append(labels);
 for(const [i,f] of b.schemaFields.entries()){
  const row=element('div',undefined,'schema-field'),label=element('input');label.placeholder='Field name';label.value=f.name;label.setAttribute('aria-label','Field '+(i+1)+' name');label.oninput=()=>{f.name=label.value;save(b);};
  const type=selectControl([['Text','Text'],['Natural','Whole number'],['Date','Date'],['Choice','Choice'],['Boolean','Yes / no']],f.type,value=>{f.type=value;save(b);renderItem(b,true);});type.setAttribute('aria-label','Field '+(i+1)+' type');const remove=element('button','−');remove.setAttribute('aria-label','Remove field '+(i+1));remove.disabled=b.schemaFields.length===1;remove.onclick=()=>{b.schemaFields.splice(i,1);b.rect.h-=46;save(b);renderItem(b,true);};row.append(label,type,remove);panel.append(row);
  if(f.type==='Choice'){const choices=element('input',undefined,'choice-values');choices.placeholder='Options: Todo, Doing, Done';choices.setAttribute('aria-label','Field '+(i+1)+' choices');choices.value=f.choices.join(', ');choices.onchange=()=>{f.choices=choices.value.split(',').map(v=>v.trim()).filter(Boolean);save(b);};panel.append(choices);}
 }
 const addField=element('button','＋ Add field','add-schema-field');addField.disabled=b.schemaFields.length>=16;addField.onclick=()=>{b.schemaFields.push({name:'',type:'Text',choices:[]});b.rect.h+=46;save(b);renderItem(b,true);nodes.get(b.id)?.querySelector('[aria-label="Field '+b.schemaFields.length+' name"]')?.focus();};panel.append(addField);
 const error=element('div','','form-error');error.setAttribute('role','status');panel.append(error);
 const create=element('button','Create collection','primary collection-create');create.onclick=async()=>{create.disabled=true;create.textContent='Checking fields…';try{const name=b.content[0]?.text.trim();if(!name)throw Error('Name your collection.');const result=await collectionCall({action:'create',event:b.creationEvent,name,fields:b.schemaFields});checkpoint('Create collection form');b.archived=true;save(b);const target=byId(b.materialTarget);if(target){target.nativeCollection=result.collection;save(target);}createForm(result.collection,null,{x:b.rect.x,y:b.rect.y});render();say('Created '+name+' · fields checked in Shrine');log('Created '+name,'local','Native typed fields · no model call');}catch(e){error.textContent=e.message;create.disabled=false;create.textContent='Create collection';}};panel.append(create);return panel;
}
''' +s[end:]
s=s.replace("function componentView(b){const panel", "function componentView(b){if(b.part==='collection-editor')return collectionEditor(b);const panel")
s=s.replace("element('div',undefined,'component'),header", "element('div',undefined,'component component-'+b.part),header")
s=s.replace("input.properties={value:{mode:'input',field:field.label,slot:field.slot}}", "input.fieldType=field.type||'Text';input.fieldChoices=field.choices||[];input.properties={value:{mode:'input',field:field.label,slot:field.slot}}")
s=s.replace("chip.append(element('small',' text'))", "chip.append(element('small',' '+(p.type==='Natural'?'number':(p.type||'Text').toLowerCase())))")
s=s.replace("shape:'Text',slot:p.slot", "shape:nativeNode(collection(b))?.properties.find(f=>f.slot===p.slot)?.type||'Text',slot:p.slot")
s=s.replace("const schema=nativeNode(id)?.properties;if(!schema)", "if(nativeNode(id)?.collectionSchema){const result=await collectionCall({action:'record',collection:id,values,event:uid()});refreshViews();renderScreen();say('Added record to '+nativeName(id));log('Created record → '+nativeName(id),'local','Native typed save');return nativeNode(result.record);}const schema=nativeNode(id)?.properties;if(!schema)")
s=s.replace("await mutation('property',{target:id,slot:p.slot,value:String(value)});", "if(nativeNode(collection(b))?.collectionSchema)await collectionCall({action:'update',collection:collection(b),record:id,field,values:{[field]:String(value)},before:{[field]:pending?.before??p.value},event:uid()});else await mutation('property',{target:id,slot:p.slot,value:String(value)});")
# Preserve per-field conflict checks while grouping form edits into the native atomic action.
needle="for(const edit of edits){const property=nativeNode(selectedId).properties.find(p=>p.label===edit.field);await mutation('property'"
repl="if(nativeNode(id)?.collectionSchema){const current=nativeRows(id).find(r=>r.id===selectedId);const all=Object.fromEntries(fields(button).map(f=>[f,values[f]??current?.[f]??'']));await collectionCall({action:'update',collection:id,record:selectedId,values:all,before:Object.fromEntries(edits.map(e=>[e.field,e.input.draftBefore])),event:uid()});for(const edit of edits){nativePending.delete(selectedId+'|'+edit.field);edit.input.valueDirty=false;save(edit.input);}refreshViews();return;}for(const edit of edits){const property=nativeNode(selectedId).properties.find(p=>p.label===edit.field);await mutation('property'"
s=s.replace(needle,repl)
# Proper typed native controls in forms and tables.
s=s.replace("function inputView(b,body){const control=element('input',undefined,'input-control');", "function inputView(b,body){const field=nativeNode(collection(b))?.properties.find(f=>f.slot===property(b,'value').slot);const control=fieldControl(field||{type:b.fieldType,choices:b.fieldChoices});control.className='input-control';")
s=s.replace("const td=element('td'),input=element('input');", "const td=element('td'),input=fieldControl(nativeNode(collection(b))?.properties.find(f=>f.label===key));")
s=s.replace("else if(b.part==='table'||b.part==='list')tableView(b,body);", "else if(b.part==='table')tableView(b,body);\n else if(b.part==='list')listView(b,body);")
s += '''
function fieldControl(field={}){const kind=field?.type||'Text';if(kind==='Choice'||kind==='Boolean'){const select=selectControl([['','Choose…'],...(kind==='Boolean'?[['true','Yes'],['false','No']]:(field.choices||[]).map(v=>[v,v]))],'',()=>{});return select;}const input=element('input');if(kind==='Natural'){input.type='number';input.min='0';input.step='1';input.inputMode='numeric';}else if(kind==='Date')input.type='date';return input;}
function listView(b,body){const data=rows(b),keys=fields(b);if(!collection(b)){const preview=element('div',undefined,'list-empty');for(let i=0;i<3;i++){const line=element('div',undefined,'list-placeholder');line.append(element('span','○'),element('span',i?'':'Items'));preview.append(line);}body.append(preview);hole(body,b,'? items');return;}const list=element('div',undefined,'collection-list');for(const row of data){const item=element('button',undefined,'list-item');item.classList.toggle('picked',row.id===selection(b));item.append(element('span',row.id===selection(b)?'●':'○','list-selection'));const words=element('span');words.append(element('strong',String(row[b.titleField||'title']??row.name??row[keys[0]]??'Untitled')));const details=keys.filter(k=>k!==(b.titleField||'title')&&k!=='name').map(k=>row[k]).filter(Boolean);if(details.length)words.append(element('small',details.join(' · ')));item.append(words);item.onclick=()=>selectRecord(b,row);list.append(item);}body.append(list);const add=element('button','＋ Add item','row-add');add.onclick=()=>createForm(collection(b));body.append(add);}
'''
p.write_text(s)
p=Path('extras/mounts/medium/workshop/index.html');s=p.read_text();start=s.index('<dialog id="material-dialog">');end=s.index('</dialog>',start)+len('</dialog>');p.write_text(s[:start]+s[end:])
