import assert from 'node:assert/strict';
import {layout,inverse,encodedValue,initials,missing} from './workshop/encodings.mjs';
const shape={rect:{w:80,h:25},scale:20,mapping:{x:'begin',width:'length',row:'crew',colour:'phase',label:'title'},properties:{x:{mode:'input',field:'begin'},width:{mode:'input',field:'length'}}};
const data=[{id:'a',begin:'2',length:'3',crew:'A',phase:'open',title:'Alpha'},{id:'b',begin:'5',length:'4',crew:'B',phase:'closed',title:'Beta'}];
const view=layout(shape,data);assert.equal(view[0].x,40);assert.equal(view[0].width,60);assert.equal(view[1].y,44);assert.equal(view[0].id,'a');assert.equal(inverse(shape,'width',80,data[0]),4);
const dial={...shape,properties:{angle:{mode:'input',field:'value',axis:{minField:'min',maxField:'max',snap:.5}}}};
const reading={value:'20',min:'10',max:'30'};assert.equal(encodedValue(dial,'angle',reading,[reading]),-90);assert.equal(inverse(dial,'angle',-67.5,reading),22.5);
dial.properties.angle.readonly=true;assert.throws(()=>inverse(dial,'angle',0,reading),/writable/);
assert.equal(initials('Ana Ortiz'),'AO');assert.equal(layout(shape,[{...data[0],begin:'not a number'}]).length,0);assert.deepEqual(missing(shape,{...data[0],begin:'not a number'}),['begin']);
assert.equal(data[0].length,'3');console.log('PASS linear/angular inversion, read-only lock, lanes, stable IDs and pure rendering');
const {inversePatch}=await import('./workshop/encodings.mjs');
const from='2026-10-09',to='2026-10-11',origin=Date.parse('2026-10-01T00:00:00Z')/86400000;
const reused={rect:{w:80,h:25},mapping:{x:'from',width:'duration'},properties:{x:{field:'from',type:'Date',mode:'input',axis:{origin,scale:30,snap:1}},width:{field:'duration',type:'Duration',mode:'input',adapter:{kind:'end-minus-start',start:'from',end:'to'},axis:{scale:30,snap:1}}}};
const interval={id:'booking',from,to};
assert.equal(encodedValue(reused,'width',interval,[interval]),60);
assert.deepEqual(inversePatch(reused,'x',270,interval),{from:'2026-10-10',to:'2026-10-12'});
assert.deepEqual(inversePatch(reused,'width',90,interval),{to:'2026-10-12'});
assert.equal(interval.to,to);assert.equal(missing(reused,interval).length,0);
console.log('PASS date interval adapter; atomic move shifts both endpoints; resize writes end only');
