// Grove physical authoring boundary. Durable scenes go through native transactions.
// No eval, generated scripts, or scenario-name dispatch. Mechanical adapters are pinned v1.
const $=s=>document.querySelector(s), scene=$('#scene'), vp=$('#viewport'), clone=structuredClone, uid=()=>crypto.randomUUID();
const NS='http://www.w3.org/2000/svg', storage='grove.authoring.drafts.v3';
const roles=['static','shows','input','movable'], gestures=['move','resize','rotate','points','select','toggle','open','action','expand','drop'];
const parts=[['text','T','Text'],['card','▣','Card'],['input','▤','Input'],['frame','⊞','Group'],['table','▦','Table'],['list','☷','List'],['board','▥','Board'],['number','#','Metric'],['chart','▥','Chart'],['image','▧','Image'],['video','▷','Video'],['audio','♫','Audio']];
const shapes=[['select','↖','Select'],['rectangle','▭','Rectangle'],['circle','◯','Circle'],['line','╱','Line'],['polygon','⬠','Polygon'],['path','∿','Path'],['label','T','Label'],['arrow','↗','Arrow']];
let blocks=[],selected=null,tool='select',using=false,zoom=1,drag=null,pointing=null,ai=false,delay=0,connected=false,modelCalls=0,fitSteps=[],history=[],historyAt=-1,previewing=false,dirty=new Set(),saving=false,queue=Promise.resolve(),fileTarget=null;
let redoStack=[],historyPreview=null;const committed=new Map(),nodes=new Map(),samples=[],frames=new Map(),files=new Map();let drafts;
try{drafts=JSON.parse(localStorage.getItem(storage)||'null');}catch{}
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const byId=id=>blocks.find(b=>b.id===id), visible=()=>blocks.filter(b=>!b.archived&&b.id!=='scene-meta');
const current=()=>byId(selected), textOf=b=>b?.content?.[0]?.text||'', rowsOf=b=>b?.items||[];function sourceOf(b){const seen=new Set();while(b?.sourceId&&byId(b.sourceId)&&!seen.has(b.id)){seen.add(b.id);b=byId(b.sourceId);}return b;}
function status(t,error=false){$('#status').textContent=t;$('#status').classList.toggle('native-error',error);}
function draft(){localStorage.setItem(storage,JSON.stringify({blocks,fitSteps,name:$('#scene-name').value}));}
function snapshot(reason){if(previewing)return;redoStack=[];history=history.slice(0,historyAt+1);history.push({blocks:clone(blocks),reason});historyAt=history.length-1;if(history.length>60){history.shift();historyAt--;}updateLog();}
function localMeasure(e){const start=e.timeStamp>1e12?e.timeStamp-performance.timeOrigin:e.timeStamp;requestAnimationFrame(()=>{samples.push(performance.now()-start);if(samples.length>600)samples.shift();const sorted=[...samples].sort((a,b)=>a-b);$('#timing').textContent='Local p95 '+sorted[Math.max(0,Math.ceil(sorted.length*.95)-1)].toFixed(1)+' ms';});}
async function call(operation,body={},event=''){const start=performance.now();const r=await fetch('/api/native',{method:'POST',headers:{'Content-Type':'application/json','X-Proof-Delay-Ms':String(delay)},body:JSON.stringify({operation,body,event})});const value=await r.json();if(!r.ok)throw new Error(value.error||'Native request failed');return value;}
function save(b){if(!b||previewing)return;dirty.add(b.id);draft();$('#save-state').textContent='Draft · saving';queue=queue.then(flush).catch(e=>{$('#save-state').textContent='Draft retained · not saved';status(e.message,true);});}
async function flush(){if(!connected)return;for(const id of [...dirty]){const b=byId(id);if(!b)continue;const prior=committed.get(id),payload=clone(b);payload.revision=(prior?.revision||0)+1;const serialized=JSON.stringify(b);const result=await call('fit/block',{block:payload,expected:prior?.revision??null},uid());const held=result.blocks.find(x=>x.id===id);committed.set(id,held);if(JSON.stringify(byId(id))===serialized){Object.assign(b,{revision:held.revision});dirty.delete(id);}draft();}$('#save-state').textContent=dirty.size?'Draft · saving':'Saved in Shrine';if(dirty.size)await flush();}
function setContent(b,text){b.content=[{...(b.content[0]||{id:uid(),kind:'text'}),text}];}
function newBlock(kind,x=80,y=80){const shape=shapes.some(s=>s[0]===kind)&&kind!=='select';return {id:uid(),kind:shape?'canvas':kind==='board'?'list':kind,parent:'',revision:0,rect:{x:Math.round(x/16)*16,y:Math.round(y/16)*16,w:shape?200:kind==='table'||kind==='board'?430:280,h:shape?140:kind==='table'||kind==='board'?280:190},content:[{id:uid(),kind:'text',text:shape?'':parts.find(p=>p[0]===kind)?.[2]||'Native view'}],part:shape?'shape':kind,shape:shape?kind:null,role:'static',gesture:'move',mapping:{},items:[],meaning:'',sourceId:null,fill:'#dae6cf',scale:16,definition:{revision:'grove.authoring/1',editable:shape||['card','frame','text'].includes(kind),slots:shape?['geometry','label']:['header','body'],inputs:['source'],outputs:['selection'],intents:[]}};}
function add(kind,p,defer=false){snapshot('Before adding '+kind);const spot=p||emptySpot(kind);const b=newBlock(kind,spot.x,spot.y);blocks.push(b);if(!defer)save(b);selected=b.id;render();inspect();status('Placed '+kind+' · no model');return b;}
function emptySpot(kind){const probe=newBlock(kind);for(let y=48;y<1600;y+=32)for(let x=48;x<2200;x+=32){if(!visible().some(b=>x<b.rect.x+b.rect.w+24&&x+probe.rect.w+24>b.rect.x&&y<b.rect.y+b.rect.h+24&&y+probe.rect.h+24>b.rect.y))return{x,y};}return{x:48,y:48};}
function rect(node,b){if(!node)return;Object.assign(node.style,{left:b.rect.x+'px',top:b.rect.y+'px',width:b.rect.w+'px',height:b.rect.h+'px',transform:b.rotation?'rotate('+b.rotation+'deg)':''});}
function fields(b){const source=sourceOf(b);return [...new Set([...(source.fields||[]).map(f=>f.name),...rowsOf(source).flatMap(row=>Object.keys(row).filter(k=>k!=='id'))])];}
function picked(b,row){sourceOf(b).selection=row.id;updateViews();}
function empty(body,title,detail){const n=el('div',undefined,'empty-state');n.append(el('b',title),el('p',detail));body.append(n);}
function sourceChip(b){if(['text','card','input','frame','image','video','audio'].includes(b.part)&&!b.sourceId)return el('span',b.file?'Local file':b.part==='input'?'Own value':'Editable','chip');const s=sourceOf(b),n=el('span',b.sourceId?'← '+textOf(s):rowsOf(b).length?rowsOf(b).length+' items':'? source','chip '+(b.sourceId||rowsOf(b).length?'confirmed':'hole'));return n;}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;}
function valueFor(b,row,channel,fallback){const f=b.mapping?.[channel];return f&&typeof row?.[f]==='number'?row[f]:fallback;}
function shapeGraphic(b){const s=svg('svg',{class:'shape-svg',viewBox:`0 0 ${b.rect.w} ${b.rect.h}`});let rows=b.sourceId?rowsOf(sourceOf(b)):rowsOf(b);if(!rows.length)rows=[null];rows.forEach((row,i)=>{const scale=b.scale||16,x=row?valueFor(b,row,'x',0)*scale:0,y=row?valueFor(b,row,'y',i*3)*scale:0,w=row?Math.max(8,valueFor(b,row,'width',b.rect.w/scale)*scale):b.rect.w,h=row?Math.max(8,valueFor(b,row,'height',2)*scale):b.rect.h;const fill=b.mapping?.colour&&row?'hsl('+hash(String(row[b.mapping.colour]))%360+' 33% 74%)':b.fill;let n;const base={fill,stroke:row&&sourceOf(b).selection===row.id?'#416ad6':'#7d9a70','stroke-width':1.6};if(b.shape==='circle')n=svg('ellipse',{cx:x+w/2,cy:y+h/2,rx:w/2,ry:h/2,...base});else if(b.shape==='line'||b.shape==='arrow')n=svg('path',{d:`M ${x} ${y+h} L ${x+w} ${y}`+(b.shape==='arrow'?` M ${x+w-14} ${y+3} L ${x+w} ${y} L ${x+w-3} ${y+14}`:''),...base,fill:'none'});else if(b.shape==='polygon')n=svg('polygon',{points:b.points?.map(p=>p.join(',')).join(' ')||`${x+w/2},${y} ${x+w},${y+h*.38} ${x+w*.8},${y+h} ${x+w*.2},${y+h} ${x},${y+h*.38}`,...base});else if(b.shape==='path')n=svg('polyline',{points:b.points?.map(p=>p.join(',')).join(' ')||`0,${h} ${w*.3},${h*.4} ${w*.6},${h*.7} ${w},0`,...base,fill:'none'});else if(b.shape==='label'){n=svg('text',{x:0,y:24,fill:'#42583a','font-size':22});n.textContent=textOf(b)||'Text';}else n=svg('rect',{x,y,width:w,height:h,rx:4,...base});if(row)n.dataset.row=row.id;s.append(n);if(row){const label=svg('text',{x:x+8,y:y+18,'font-size':11,fill:'#344b2d','pointer-events':'none'});label.textContent=row.title??row.name??row[fields(b)[0]]??'';s.append(label);if(b.role==='movable'){const handle=svg('rect',{x:x+w-5,y:y+h/2-6,width:10,height:12,fill:'#fff',stroke:'#416ad6','data-row':row.id,'data-record-resize':'true'});s.append(handle);}}});return s;}
function hash(s){let n=0;for(const c of s)n=(n*31+c.charCodeAt(0))>>>0;return n;}
function aggregate(b){const rows=rowsOf(sourceOf(b)),field=b.field,values=rows.map(r=>Number(r[field])).filter(Number.isFinite);if(b.formula==='sum')return values.reduce((a,v)=>a+v,0);if(b.formula==='area')return rows.reduce((a,r)=>a+(Number(r[b.mapping.width||'width'])||0)*(Number(r[b.mapping.height||'height'])||0),0);if(b.formula==='max')return values.length?Math.max(...values):0;return rows.length;}
function componentGraphic(b){const panel=el('div',undefined,'component'),header=el('div',undefined,'component-title'),body=el('div',undefined,'component-body');header.append(el('span',textOf(b)),sourceChip(b));panel.append(header,body);const src=sourceOf(b),rows=rowsOf(src);
 if(b.part==='text'||b.part==='card'){const t=el('textarea',undefined,'rawtext');t.placeholder=b.part==='card'?'Describe this thing…':'Write here…';t.value=b.notes||'';t.onfocus=()=>snapshot('Before editing text');t.oninput=()=>{b.notes=t.value;save(b);};body.append(t);}
 else if(b.part==='frame'){empty(body,'A place for parts','Drag shapes or components inside this group.');}
 else if(b.part==='input'){const input=el('input',undefined,'full');input.placeholder=b.placeholder||'Enter a value';input.value=b.value||'';input.onfocus=()=>snapshot('Before editing value');input.oninput=()=>{b.value=input.value;save(b);};body.append(input,el('p',b.sourceId?'Linked source requires a declared write field.':'Own value · saved with this component','hint'));}
 else if(b.part==='number'){body.append(el('div',String(Math.round(aggregate(b)*100)/100),'metric'),el('span',(b.formula||'count')+'('+textOf(src)+')','hint'));if(!b.sourceId&&!rows.length)body.append(el('p','Point at a collection in the inspector.','chip hole'));}
 else if(b.part==='table'||b.part==='list'){if(!rows.length)empty(body,'Your data goes here','Add rows, paste your own data, or point at a collection.');else{const table=el('table',undefined,'table'),head=el('tr');const keys=fields(b);keys.forEach(k=>head.append(el('th',k)));table.append(head);rows.forEach(row=>{const tr=el('tr');tr.classList.toggle('picked',src.selection===row.id);tr.onclick=()=>picked(b,row);keys.forEach(k=>{const td=el('td'),input=el('input');input.value=row[k]??'';input.setAttribute('aria-label',k);input.type=typeof row[k]==='number'?'number':typeof row[k]==='boolean'?'checkbox':'text';if(typeof row[k]==='boolean')input.checked=row[k];input.onchange=()=>{snapshot('Before editing '+k);row[k]=typeof row[k]==='number'?Number(input.value):typeof row[k]==='boolean'?input.checked:input.value;save(src);updateViews(b.id);};td.append(input);tr.append(td);});table.append(tr);});body.append(table);}const add=el('button','＋ Add row');add.onclick=()=>{snapshot('Before adding row');const row={id:uid()};const keys=fields(b);(keys.length?keys:['title']).forEach(k=>row[k]=(src.fields||[]).find(f=>f.name===k)?.type==='number'||typeof rows[0]?.[k]==='number'?0:'');src.items.push(row);save(src);updateViews();};body.append(add);}
 else if(b.part==='board'){const key=b.groupField||'status',groups=[...new Set(rows.map(r=>String(r[key]??'Unassigned')))];if(!groups.length)empty(body,'A board, ready for your items','Point at a collection and choose its group field.');const board=el('div',undefined,'board');groups.forEach(g=>{const col=el('div',undefined,'column'),members=rows.filter(r=>String(r[key]??'Unassigned')===g);const h=el('h4',g);h.append(el('span',members.length));col.append(h);col.ondragover=e=>{if(e.dataTransfer.types.includes('application/grove-row'))e.preventDefault();};col.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('application/grove-row'),row=rows.find(r=>r.id===id);if(!row)return;snapshot('Before moving item');row[key]=g;save(src);updateViews();};members.forEach(row=>{const card=el('div',row.title??row.name??row[fields(b)[0]],'record-card');card.classList.toggle('picked',src.selection===row.id);card.draggable=using;card.ondragstart=e=>{e.dataTransfer.setData('application/grove-row',row.id);e.stopPropagation();};card.onclick=()=>picked(b,row);col.append(card);});board.append(col);});body.append(board);}
 else if(b.part==='chart'){if(!rows.length)empty(body,'A view of your data','Point at a collection, then choose a quantity or grouping.');else{const s=svg('svg',{viewBox:'0 0 300 160',width:'100%',height:'100%'});const group=b.groupField;const values=group?[...new Set(rows.map(r=>String(r[group])))].map(k=>({name:k,value:rows.filter(r=>String(r[group])===k).length,ids:rows.filter(r=>String(r[group])===k).map(r=>r.id)})):rows.map(r=>({name:String(r.title??r.name??''),value:Number(r[b.field])||0,ids:[r.id]}));const max=Math.max(1,...values.map(v=>Math.abs(v.value)));values.forEach((v,i)=>{const w=260/values.length,x=25+i*w,h=Math.max(1,v.value/max*110),bar=svg('rect',{x,y:125-h,width:Math.max(2,w-10),height:h,rx:3,fill:v.ids.includes(src.selection)?'#416ad6':'#93ac82'});const title=svg('title');title.textContent=v.name+': '+v.value;bar.append(title);bar.onpointerdown=e=>e.stopPropagation();bar.onclick=()=>{src.selection=v.ids[0];updateViews();};const label=svg('text',{x:x+2,y:145,'font-size':9,fill:'#718269'});label.textContent=v.name.slice(0,12);s.append(bar,label);});body.append(s);}}
 else if(['image','video','audio'].includes(b.part)){const url=files.get(b.id)||b.url;if(url){const media=el(b.part==='image'?'img':b.part);media.src=url;media.className=b.part==='image'?'image-view':'media';if(b.part!=='image'){media.controls=true;media.onloadedmetadata=()=>{if(b.playhead)media.currentTime=b.playhead;};media.onseeked=()=>{b.playhead=media.currentTime;save(b);};}body.append(media);}else empty(body,'Bring your own '+b.part,'Choose a file. Media stays in this browser; metadata is saved in Shrine.');const input=el('input',undefined,'file-input');input.type='file';input.accept=b.part+'/*';input.onchange=async()=>{const file=input.files[0];if(!file)return;await putFile(b.id,file);files.set(b.id,URL.createObjectURL(file));b.file={name:file.name,type:file.type,size:file.size};save(b);renderItem(b);};body.append(input);}
 else if(b.part==='native'){const held=frames.get(b.id);if(held){body.innerHTML=held.html;body.querySelectorAll('script,iframe,object,embed,link,meta').forEach(n=>n.remove());for(const n of body.querySelectorAll('*'))for(const a of [...n.attributes])if(/^on/i.test(a.name)||['srcdoc','action','formaction'].includes(a.name))n.removeAttribute(a.name);body.onclick=async e=>{const item=e.target.closest('[data-grove-act]');if(!item)return;try{await call('native/act',{subject:b.source.subject,basis:held.basis,key:item.dataset.groveKey,viewport:[],parameters:[],arguments:[]},uid());await nativeFrame(b);}catch(error){status(error.message,true);}};}else empty(body,'Native surface','Loading its established Grove presentation…');}
 return panel;}
function renderItem(b){if(previewing)return;let node=nodes.get(b.id);if(!node){node=el('section',undefined,'item');node.dataset.id=b.id;scene.append(node);nodes.set(b.id,node);}rect(node,b);node.classList.toggle('selected',selected===b.id);node.classList.toggle('pointable',!!pointing);if(node.contains(document.activeElement)&&document.activeElement.matches('input,textarea,select'))return;node.replaceChildren();const grip=el('div',textOf(b)||b.shape||b.part,'grab');grip.dataset.grip='true';node.append(grip,b.part==='shape'?shapeGraphic(b):componentGraphic(b));if(b.part==='shape'&&b.shape!=='label'&&textOf(b)){const label=el('span',textOf(b),'shape-label');node.append(label);}const h=el('button',undefined,'resize');h.setAttribute('aria-label','Resize '+(textOf(b)||b.shape));node.append(h);if(b.question)node.append(el('span','? '+b.question,'badge'));}
function render(){for(const[id,node]of nodes){if(!visible().some(b=>b.id===id)){node.remove();nodes.delete(id);}}visible().forEach(renderItem);$('#empty').hidden=visible().length>0;renderLinks();material();}
function updateViews(except){visible().filter(b=>b.id!==except).forEach(renderItem);renderLinks();material();}
function renderLinks(){const s=$('#links');s.replaceChildren();visible().filter(b=>b.sourceId&&byId(b.sourceId)).forEach(b=>{const a=byId(b.sourceId);const x=a.rect.x+a.rect.w,y=a.rect.y+a.rect.h/2,xx=b.rect.x,yy=b.rect.y+b.rect.h/2;s.append(svg('path',{d:`M${x},${y} C${x+60},${y} ${xx-60},${yy} ${xx},${yy}`,class:'arrowline'}));});}
function select(id){selected=id;nodes.forEach((n,k)=>n.classList.toggle('selected',k===id));inspect();}
function formLabel(parent,name,control){control.id=control.id||uid();const label=el('label',name);label.htmlFor=control.id;parent.append(label,control);return control;}
function selectField(options,value,callback){const s=el('select');for(const [v,t]of options.map(v=>Array.isArray(v)?v:[v,v])){const o=el('option',t);o.value=v;s.append(o);}s.value=value||'';s.onchange=()=>callback(s.value);return s;}
function change(b,field,value,reason){snapshot('Before '+reason);b[field]=value;save(b);render();addStep(reason,'explicit',b.id,'applied');}
function inspect(){const pane=$('#inspector-body'),b=current();$('#inspector-empty').hidden=!!b;pane.hidden=!b;if(!b)return;pane.replaceChildren();const title=el('div',undefined,'inspect-title'),name=el('input');name.value=textOf(b);name.placeholder=b.shape||b.part;name.setAttribute('aria-label','Item name');name.onchange=()=>{snapshot('Before naming');setContent(b,name.value);save(b);render();};title.append(name);pane.append(title,el('span',b.part==='shape'?'Shape · yours to define':'Grove '+b.part+' · revision 1','eyebrow'));
 const section=(n,title)=>{const s=el('section',undefined,'section'),h=el('h3');h.append(el('span',n),document.createTextNode(title));s.append(h);pane.append(s);return s;};
 let s=section('01','What is it?');const modes=el('div',undefined,'modes');[['static','Just looks'],['shows','Shows data'],['input','Input'],['movable','Movable']].forEach(([v,label])=>{const btn=el('button',label);btn.setAttribute('aria-pressed',String(b.role===v));btn.onclick=()=>{change(b,'role',v,'Role → '+label);inspect();};modes.append(btn);});s.append(modes);
 s=section('02','Mouse & dimensions');if(b.part==='shape'||['card','frame','text'].includes(b.part))formLabel(s,'Interaction',selectField(['move','resize','select','toggle','open','expand','action','drop'],b.gesture,v=>change(b,'gesture',v,'Gesture → '+v)));if(b.part!=='shape')s.append(el('p','Prepared controls keep their built-in gestures. Roles describe their outer composition.','hint'));
 for(const channel of (b.role==='movable'||b.part==='shape'&&b.sourceId?['x','y','width','height','colour']:[])){const line=el('div',undefined,'mapping');line.dataset.channel=channel;line.append(el('span',channel),el('span','='),selectField([['','— visual only'],...fields(b)],b.mapping?.[channel],v=>{snapshot('Before mapping');b.mapping[channel]=v;save(b);render();addStep(channel+' → '+(v||'visual only'),'explicit',b.id,'applied');}));s.append(line);}
 const scale=el('input');scale.type='number';scale.min='1';scale.value=b.scale||16;scale.onchange=()=>change(b,'scale',Math.max(1,Number(scale.value)),'Scale changed');formLabel(s,'Pixels per data unit',scale);
 s=section('03','What does it mean?');const meaning=el('textarea');meaning.rows=3;meaning.placeholder='This bar is one task. Its position is the start time.';meaning.value=b.meaning||'';meaning.onchange=()=>{b.meaning=meaning.value;save(b);};formLabel(s,'A sentence, if needed',meaning);if(['number','chart'].includes(b.part)){formLabel(s,'Calculation',selectField(['count','sum','max','area'],b.formula||'count',v=>change(b,'formula',v,'Calculation → '+v)));formLabel(s,'Value field',selectField([['','— choose'],...fields(b)],b.field,v=>change(b,'field',v,'Value → '+v)));}if(['board','chart'].includes(b.part))formLabel(s,'Group by',selectField([['','— no grouping'],...fields(b)],b.groupField,v=>change(b,'groupField',v,'Group → '+v)));
 s=section('04','What does it affect?');if(b.sourceId){s.append(el('span','Reads '+textOf(sourceOf(b)),'chip confirmed'));const clear=el('button','Disconnect');clear.onclick=()=>{change(b,'sourceId',null,'Disconnected source');inspect();};s.append(clear);}const point=el('button',pointing?'Click a source on the canvas…':'◎ Point at a source');point.className='full';point.onclick=()=>{pointing=b.id;status('Click a component or shape to use its records. Escape cancels.');render();};s.append(point,el('p','Mappings state the fields that a drag writes. Other views sharing that source update locally.','hint'));
 const schema=el('details',undefined,'section');schema.open=['table','list','board'].includes(b.part);schema.append(el('summary','Record fields'),el('p','Declare the fields first. Add records in a Table or List.','hint'));const fieldName=el('input');fieldName.placeholder='Field name';fieldName.setAttribute('aria-label','New field name');const fieldType=selectField(['text','number','boolean'],'text',()=>{});fieldType.setAttribute('aria-label','New field type');const addField=el('button','＋ Add field');addField.onclick=()=>{const name=fieldName.value.trim();if(!name||name==='id'||fields(b).includes(name)){status('Choose a new field name.',true);return;}snapshot('Before adding field');const src=sourceOf(b);src.fields=[...(src.fields||[]),{name,type:fieldType.value}];for(const row of rowsOf(src))row[name]=fieldType.value==='number'?0:fieldType.value==='boolean'?false:'';save(src);render();inspect();};schema.append(fieldName,fieldType,addField);s.append(schema);
 const data=el('button','Advanced · JSON records');data.className='full';data.onclick=()=>{fileTarget=b.id;$('#data-json').value=JSON.stringify(rowsOf(b),null,2);$('#data-error').textContent='';$('#data-dialog').showModal();};s.append(data);
 const remove=el('button','Remove from scene','danger');remove.onclick=()=>{snapshot('Before removal');b.archived=true;save(b);selected=null;render();inspect();};const duplicate=el('button','Duplicate');duplicate.onclick=()=>{snapshot('Before duplicate');const c=clone(b);c.id=uid();c.revision=0;c.rect.x+=32;c.rect.y+=32;c.content=c.content.map(v=>({...v,id:uid()}));c.items=c.items.map(v=>({...v,id:uid()}));blocks.push(c);save(c);select(c.id);render();};pane.append(el('div','', 'section'),duplicate,remove);renderFitLog(pane);
}
function addStep(reason,origin,target,state='proposed',patch=null){fitSteps.push({id:uid(),reason,origin,target,state,patch,basis:clone(byId(target)),time:Date.now()});draft();updateLog();}
function updateLog(){const old=$('#fit-log');if(old)old.remove();if(current())renderFitLog($('#inspector-body'));}
function renderFitLog(pane){if($('#fit-log'))return;const section=el('section',undefined,'section');section.id='fit-log';section.append(el('h3','Fit history'),el('p','Each suggestion is independent. Uncertainty stays local.','hint'));fitSteps.slice(-12).reverse().forEach(step=>{const row=el('div',undefined,'fit-step');row.append(el('p',step.reason),el('span',step.origin+' · '+step.state,'chip '+(step.state==='proposed'?'proposal':step.state==='applied'?'confirmed':'hole')));if(step.state==='proposed'){for(const [name,state]of [['Accept','applied'],['Reject','rejected']]){const button=el('button',name);button.onclick=()=>{if(state==='applied'){const b=byId(step.target);if(!b||JSON.stringify(b)!==JSON.stringify(step.basis)){step.state='stale';status('This item changed. Review a fresh suggestion; current edits are retained.',true);updateLog();return;}snapshot('Before accepting '+step.reason);const changes=clone(step.patch);if(changes.mapping)changes.mapping={...b.mapping,...changes.mapping};Object.assign(b,changes);save(b);render();}step.state=state;draft();inspect();};row.append(button);}}section.append(row);});if(history.length){const range=el('input');range.type='range';range.min='0';range.max=String(history.length);range.value=String(history.length);range.setAttribute('aria-label','Inspect history');const restore=el('button','Restore this point');restore.hidden=true;range.oninput=()=>{const i=+range.value;historyPreview=i===history.length?null:i;const live=blocks;if(historyPreview!==null)blocks=clone(history[i].blocks);render();blocks=live;scene.style.pointerEvents=historyPreview===null?'':'none';restore.hidden=historyPreview===null;status(historyPreview===null?'Current scene':'Preview: '+history[i].reason+' · no state changed');};restore.onclick=()=>{if(historyPreview===null)return;const prior=history[historyPreview];scene.style.pointerEvents='';historyPreview=null;snapshot('Before history restore');restoreScene(prior.blocks);status('Restored '+prior.reason);};section.append(restore);section.append(range);}pane.append(section);}
function material(){$('#scene-material').replaceChildren();visible().filter(b=>rowsOf(b).length||b.part==='native').forEach(b=>{const btn=el('button',(textOf(b)||b.shape)+' · '+rowsOf(b).length);btn.onclick=()=>{if(pointing){bindSource(pointing,b.id);}else select(b.id);};btn.draggable=true;btn.ondragstart=e=>e.dataTransfer.setData('application/grove-source',b.id);$('#scene-material').append(btn);});}
function bindSource(target,source){if(target===source){pointing=null;return;}let at=byId(source);const seen=new Set([target]);while(at){if(seen.has(at.id)){status('That would create a source cycle.',true);return;}seen.add(at.id);at=byId(at.sourceId);}const b=byId(target);change(b,'sourceId',source,'Source → '+textOf(byId(source)));pointing=null;render();inspect();}
function position(e){const box=scene.getBoundingClientRect();return{x:(e.clientX-box.left)/zoom,y:(e.clientY-box.top)/zoom};}
function snap(value){return Math.max(0,Math.round(value/16)*16);}
scene.onpointerdown=e=>{if(e.button!==0)return;const node=e.target.closest('.item'),b=node&&byId(node.dataset.id),p=position(e);if(pointing&&b){e.preventDefault();bindSource(pointing,b.id);return;}if(b&&e.target.closest('input,textarea,select,video,audio,button:not(.resize)')){select(b.id);return;}if(b){select(b.id);if(using&&b.part!=='shape')return;if(using&&b.role!=='movable'){if(b.gesture==='select'){b.selection=true;updateViews();}else if(b.gesture==='toggle'){b.toggled=!b.toggled;save(b);status('Toggled '+(textOf(b)||b.shape));}else if(['open','expand'].includes(b.gesture)){document.body.classList.add('show-inspector');inspect();status('Opened item details.');}else if(b.gesture==='action'||b.gesture==='drop'){status('This intent still needs a checked native destination.',true);}return;}if(using&&b.role==='movable'&&!['move','resize'].includes(b.gesture)){status('This gesture needs an implementation; no state changed.',true);return;}const rowId=e.target.dataset.row,src=sourceOf(b),row=rowId&&rowsOf(src).find(r=>r.id===rowId);drag={mode:row?'record':e.target.closest('.resize')?'resize':'move',b,node,start:p,before:clone(b),row,src,rowBefore:row&&clone(row),resizing:!!e.target.dataset.recordResize||b.gesture==='resize'};}else if(tool!=='select'){const b=add(tool,p,true);b.rect.w=32;b.rect.h=32;if(['path','polygon'].includes(tool))b.points=[[0,0]];drag={mode:'draw',b,node:nodes.get(b.id),start:p,before:clone(b)};}else{select(null);return;}e.preventDefault();scene.setPointerCapture(e.pointerId);localMeasure(e);};
scene.onpointermove=e=>{if(!drag)return;const p=position(e),d=drag,dx=p.x-d.start.x,dy=p.y-d.start.y;if(!d.changed&&Math.hypot(dx,dy)<3)return;if(!d.changed){if(d.mode!=='draw')snapshot('Before gesture');d.changed=true;}if(d.mode==='record'){const row=d.row,old=d.rowBefore,scale=d.b.scale||16;const channels=d.resizing?['width']:['x','y'];for(const channel of channels){const field=d.b.mapping[channel];if(!field)continue;const delta=channel==='y'?dy:dx;row[field]=Math.round(((Number(old[field])||0)+delta/scale)*100)/100;if(channel==='width')row[field]=Math.max(.1,row[field]);}updateViews();}else if(d.mode==='move'){d.b.rect.x=snap(d.before.rect.x+dx);d.b.rect.y=snap(d.before.rect.y+dy);const children=blocks.filter(b=>b.parent===d.b.id);for(const child of children){child.rect.x+=d.b.rect.x-(d.lastX??d.before.rect.x);child.rect.y+=d.b.rect.y-(d.lastY??d.before.rect.y);rect(nodes.get(child.id),child);}d.lastX=d.b.rect.x;d.lastY=d.b.rect.y;rect(d.node,d.b);renderLinks();}else{d.b.rect.w=Math.max(32,snap((d.mode==='draw'?0:d.before.rect.w)+dx));d.b.rect.h=Math.max(32,snap((d.mode==='draw'?0:d.before.rect.h)+dy));if(d.mode==='draw'&&['path','polygon'].includes(d.b.shape))d.b.points.push([p.x-d.b.rect.x,p.y-d.b.rect.y]);renderItem(d.b);}localMeasure(e);};
scene.onpointerup=e=>{if(!drag)return;const d=drag;drag=null;if(!d.changed&&d.mode!=='draw'){if(scene.hasPointerCapture(e.pointerId))scene.releasePointerCapture(e.pointerId);return;}if(d.mode==='move'){const parent=visible().filter(b=>b.id!==d.b.id&&b.part==='frame'&&d.b.rect.x>=b.rect.x&&d.b.rect.y>=b.rect.y&&d.b.rect.x+d.b.rect.w<=b.rect.x+b.rect.w&&d.b.rect.y+d.b.rect.h<=b.rect.y+b.rect.h).sort((a,b)=>a.rect.w*a.rect.h-b.rect.w*b.rect.h)[0];if(!blocks.some(b=>b.parent===d.b.id))d.b.parent=parent?.id||'';blocks.filter(b=>b.parent===d.b.id).forEach(save);}save(d.mode==='record'?d.src:d.b);tool='select';if(scene.hasPointerCapture(e.pointerId))scene.releasePointerCapture(e.pointerId);render();inspect();localMeasure(e);};scene.onpointercancel=e=>{if(!drag)return;const d=drag;Object.assign(d.b,d.before);if(d.row)Object.assign(d.row,d.rowBefore);drag=null;render();};
for(const[k,icon,label]of shapes){const b=el('button');b.append(el('i',icon),document.createTextNode(label));b.onclick=()=>{tool=k;status(k==='select'?'Select an item':'Drag to draw '+label);$('#tool-hint').textContent=label;};$('#draw-tools').append(b);}for(const[k,icon,label]of parts){const b=el('button');b.append(el('i',icon),document.createTextNode(label));b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/grove-part',k);b.onclick=()=>add(k);$('#parts').append(b);}
scene.ondragover=e=>{if([...e.dataTransfer.types].some(t=>t.startsWith('application/grove')))e.preventDefault();};scene.ondrop=e=>{const part=e.dataTransfer.getData('application/grove-part'),source=e.dataTransfer.getData('application/grove-source'),native=e.dataTransfer.getData('application/grove-native');if(!part&&!source&&!native)return;e.preventDefault();const target=e.target.closest('.item');if(part)add(part,position(e));else if(source&&target)bindSource(target.dataset.id,source);else if(native)dropNative(native,position(e));};
$('#arrange').onclick=()=>{using=false;$('#arrange').setAttribute('aria-pressed','true');$('#use').setAttribute('aria-pressed','false');status('Arrange: drag components by their frame.');};$('#use').onclick=()=>{using=true;$('#arrange').setAttribute('aria-pressed','false');$('#use').setAttribute('aria-pressed','true');status('Use: operate controls and mapped shapes.');render();};
$('#fit').onclick=()=>{const targets=selected?[current(),...visible().filter(b=>b.parent===selected)]:visible();targets.forEach(b=>{const next={...b.rect,x:snap(b.rect.x),y:snap(b.rect.y),w:Math.max(32,snap(b.rect.w)),h:Math.max(32,snap(b.rect.h))};if(JSON.stringify(next)!==JSON.stringify(b.rect))addStep('Snap '+(textOf(b)||b.shape)+' to the 16 px grid.','engine',b.id,'proposed',{rect:next});});status('Layout checked locally. Only proposed geometry changes; zero model calls.');inspect();};
function restoreScene(prior){const old=clone(blocks);blocks=clone(prior);for(const b of old)if(!byId(b.id))blocks.push({...b,archived:true});blocks.forEach(b=>{const held=committed.get(b.id);if(held)b.revision=held.revision;save(b);});selected=null;render();inspect();}
$('#history').onclick=()=>{if(historyAt<0)return;const prior=history[historyAt--];redoStack.push(clone(blocks));restoreScene(prior.blocks);status('Undid: '+prior.reason);};
$('#redo').onclick=()=>{if(!redoStack.length)return;const next=redoStack.pop();historyAt++;restoreScene(next);status('Redid last change.');};
$('#save-data').onclick=e=>{e.preventDefault();try{const rows=JSON.parse($('#data-json').value);if(!Array.isArray(rows)||rows.length>500||rows.some(r=>!r||Array.isArray(r)||typeof r!=='object'||Object.values(r).some(v=>v!==null&&!['number','string','boolean'].includes(typeof v))))throw new Error('Use up to 500 flat records with text, numbers or booleans.');const ids=new Set();for(const r of rows){r.id=r.id||uid();if(ids.has(r.id))throw new Error('Record identities must be unique.');ids.add(r.id);}snapshot('Before editing records');const b=byId(fileTarget);b.items=rows;save(b);$('#data-dialog').close();updateViews();inspect();}catch(error){$('#data-error').textContent=error.message;}};
$('#ai').onclick=()=>{ai=!ai;$('#ai').textContent=ai?'AI on':'AI off';$('#ai').setAttribute('aria-pressed',String(ai));};
$('#interpret').onclick=async()=>{if(!ai){status('AI is off. Explicit mappings and established interactions still work.');return;}const b=current();if(!b?.meaning?.trim()){status('Select an item and add a meaning sentence. Your scene is unchanged.');return;}let basis;$('#interpret').disabled=true;modelCalls++;$('#calls').textContent=modelCalls+' model calls';status('Reading the selected meaning and its scene context…');try{await queue;basis=clone(b);const r=await fetch('/api/interpret',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.id,revision:b.revision})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Interpretation unavailable');if(JSON.stringify(byId(b.id))!==JSON.stringify(basis)){status('The item changed; interpretation retained as stale.',true);return;}for(const patch of result.patches||[])addStep(patch.reason,'model',b.id,'proposed',patch.changes);for(const q of result.questions||[])addStep(q,'model',b.id,'question');status('Suggestions ready · '+Math.round(result.elapsed_ms)+' ms · '+(result.output_bytes||0)+' bytes');inspect();}catch(error){status(error.message+' · working scene retained',true);}finally{$('#interpret').disabled=false;}};
$('#delay').onclick=()=>{delay=delay?0:2000;$('#delay').textContent=delay?'Network +2 seconds':'Network delay off';};
function setZoom(z){zoom=Math.max(.5,Math.min(1.5,z));scene.style.transform='scale('+zoom+')';$('#zoom-label').textContent=Math.round(zoom*100)+'%';}$('#zoom-in').onclick=()=>setZoom(zoom+.1);$('#zoom-out').onclick=()=>setZoom(zoom-.1);
$('#export').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,blocks,fitSteps,localPaintOpportunityMs:samples,modelCalls},null,2)],{type:'application/json'}));a.download='grove-scene.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'){pointing=null;tool='select';historyPreview=null;scene.style.pointerEvents='';render();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'#redo':'#history').click();return;}const b=current();if(!b)return;if(['Backspace','Delete'].includes(e.key)){e.preventDefault();snapshot('Before removal');b.archived=true;save(b);select(null);render();}if(e.key.startsWith('Arrow')){e.preventDefault();snapshot('Before nudge');const amount=e.shiftKey?16:1;if(e.key==='ArrowLeft')b.rect.x=Math.max(0,b.rect.x-amount);if(e.key==='ArrowRight')b.rect.x+=amount;if(e.key==='ArrowUp')b.rect.y=Math.max(0,b.rect.y-amount);if(e.key==='ArrowDown')b.rect.y+=amount;save(b);render();}});

async function browse(subject='/0x11/app'){try{const data=await call('native/discover',{subject});const pane=$('#namespace');pane.replaceChildren();if(subject!=='/0x11/app'){const up=el('button','‹ Parent');up.onclick=()=>browse(subject.slice(0,subject.lastIndexOf('/')));pane.append(up);}for(const c of data.children){const btn=el('button',c.label||c.subject.split('/').at(-1));btn.title=c.subject;btn.draggable=true;btn.onclick=()=>browse(c.subject);btn.ondblclick=()=>dropNative(c.subject,{x:vp.scrollLeft/zoom+60,y:vp.scrollTop/zoom+80});btn.ondragstart=e=>e.dataTransfer.setData('application/grove-native',c.subject);pane.append(btn);}const place=el('button','＋ Place this native view');place.onclick=()=>dropNative(subject,{x:vp.scrollLeft/zoom+60,y:vp.scrollTop/zoom+80});pane.append(place);}catch(error){status(error.message,true);}}
async function dropNative(subject,p){try{const frame=await call('native/frame',{subject,viewport:[]});const b=newBlock('card',p.x,p.y);b.kind='material';b.part='native';b.source={subject,revision:frame.basis.owner.case};b.rect.w=480;b.rect.h=300;setContent(b,subject.split('/').at(-1));frames.set(b.id,frame);snapshot('Before native material');blocks.push(b);save(b);selected=b.id;render();inspect();}catch(error){status(error.message+' · no fictional replacement created',true);}}
async function nativeFrame(b){try{frames.set(b.id,await call('native/frame',{subject:b.source.subject,viewport:[]}));renderItem(b);}catch(error){status(error.message,true);}}
$('#refresh-ns').onclick=()=>browse();
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('grove-authoring-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function putFile(id,file){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});d.close();}
async function getFile(id){const d=await db();const file=await new Promise((resolve,reject)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});d.close();return file;}
async function start(){try{await fetch('/connect',{method:'POST'});const state=await call('fit/read');blocks=state.blocks;blocks.forEach(b=>committed.set(b.id,clone(b)));connected=true;if(drafts?.blocks){for(const b of drafts.blocks){const existing=byId(b.id);if(!existing&&b.revision===0){blocks.push(b);dirty.add(b.id);}else if(existing&&b.revision===existing.revision&&JSON.stringify(existing)!==JSON.stringify(b)){Object.assign(existing,b);dirty.add(b.id);}}fitSteps=drafts.fitSteps||[];$('#scene-name').value=drafts.name||'Untitled scene';}for(const b of blocks){if(b.file){const file=await getFile(b.id);if(file)files.set(b.id,URL.createObjectURL(file));}if(b.part==='native')nativeFrame(b);}render();inspect();$('#save-state').textContent='Saved in Shrine';await flush();browse();}catch(error){blocks=drafts?.blocks||[];render();status(error.message+' · local drafts retained',true);$('#save-state').textContent='Native unavailable';}}
$('#scene-name').onchange=draft;window.groveEvidence=()=>({modelCalls,localPaintOpportunityMs:[...samples],blocks:visible().length,pendingSaves:dirty.size});start();

$('#palette-toggle').onclick=()=>document.body.classList.toggle('show-palette');
$('#inspector-toggle').onclick=()=>document.body.classList.toggle('show-inspector');
